image: node:18.20.4
pages:
  cache:
    paths:
      - node_modules/
  script:
    - npm install -g @angular/cli@18.1.1
    - npm install
    - npm run buildProd
  artifacts:
    paths:
      - public
  only:
    - master
    - pages